# Generated by Django 4.2.8 on 2023-12-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_court"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="age",
            field=models.IntegerField(default=18),
        ),
    ]
