# Generated by Django 4.2.8 on 2023-12-12 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_alter_member_age"),
    ]

    operations = [
        migrations.RenameField(
            model_name="court",
            old_name="Type",
            new_name="type",
        ),
    ]
